/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 GamingJoin.glb --transform --simplify 
Files: GamingJoin.glb [52.47MB] > GamingJoin-transformed.glb [1.97MB] (96%)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/GamingJoin-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Radiator_3x120_EKweb" position={[-1.52, 3.103, -3.041]} rotation={[Math.PI / 2, 0, 0]} scale={3.11}>
          <mesh name="BezierCurve001" geometry={nodes.BezierCurve001.geometry} material={materials.PaletteMaterial005} position={[0, 0, -0.063]} />
          <mesh name="BezierCurve004" geometry={nodes.BezierCurve004.geometry} material={materials.PaletteMaterial005} position={[0, 0, -0.063]} />
          <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials.PaletteMaterial001} position={[0, 0.038, -0.126]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.064, 0.064, 0.009]} />
          <group name="FAN_Blade" position={[0, 0.037, 0.123]}>
            <mesh name="Fan001" geometry={nodes.Fan001.geometry} material={materials.PaletteMaterial006} />
            <mesh name="Fan001_1" geometry={nodes.Fan001_1.geometry} material={materials.PaletteMaterial005} />
            <mesh name="Fan001_2" geometry={nodes.Fan001_2.geometry} material={materials.PaletteMaterial007} />
            <mesh name="Fan001_3" geometry={nodes.Fan001_3.geometry} material={materials.PaletteMaterial002} />
          </group>
          <group name="FAN_Blade002" position={[0, 0.037, 0]}>
            <mesh name="Fan001" geometry={nodes.Fan001.geometry} material={materials.PaletteMaterial006} />
            <mesh name="Fan001_1" geometry={nodes.Fan001_1.geometry} material={materials.PaletteMaterial005} />
            <mesh name="Fan001_2" geometry={nodes.Fan001_2.geometry} material={materials.PaletteMaterial007} />
            <mesh name="Fan001_3" geometry={nodes.Fan001_3.geometry} material={materials.PaletteMaterial002} />
          </group>
          <group name="FAN_Blade003" position={[0, 0.037, -0.124]}>
            <mesh name="Fan001" geometry={nodes.Fan001.geometry} material={materials.PaletteMaterial006} />
            <mesh name="Fan001_1" geometry={nodes.Fan001_1.geometry} material={materials.PaletteMaterial005} />
            <mesh name="Fan001_2" geometry={nodes.Fan001_2.geometry} material={materials.PaletteMaterial007} />
            <mesh name="Fan001_3" geometry={nodes.Fan001_3.geometry} material={materials.PaletteMaterial002} />
          </group>
          <mesh name="Fan_Housing003" geometry={nodes.Fan_Housing003.geometry} material={materials.PaletteMaterial002} />
        </group>
        <group name="E_Cello_feng_ling_MCP001" position={[-4.141, 1.081, -3.36]} rotation={[0, Math.PI / 2, 0]} scale={2.217}>
          <group name="Cello" rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Circle028" geometry={nodes.Circle028.geometry} material={materials['wood.1']} />
            <mesh name="Circle028_1" geometry={nodes.Circle028_1.geometry} material={materials.PaletteMaterial009} />
            <mesh name="Circle028_2" geometry={nodes.Circle028_2.geometry} material={materials.PaletteMaterial010} />
            <mesh name="Circle028_3" geometry={nodes.Circle028_3.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Circle028_4" geometry={nodes.Circle028_4.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Circle028_5" geometry={nodes.Circle028_5.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Circle028_6" geometry={nodes.Circle028_6.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Circle028_7" geometry={nodes.Circle028_7.geometry} material={materials.PaletteMaterial011} />
          </group>
        </group>
        <group name="Cast_Away_Volleyball" position={[-2.732, 4.711, -4.494]} rotation={[Math.PI, -0.698, Math.PI]} scale={2.567}>
          <mesh name="VolleyBallFinished" geometry={nodes.VolleyBallFinished.geometry} material={materials.VolleyBall} position={[0.18, 0.107, 0.151]}>
            <mesh name="InflationValave" geometry={nodes.InflationValave.geometry} material={materials.PaletteMaterial001} />
          </mesh>
        </group>
        <group name="Guitar_made_of_Bezier_curve" position={[-4.679, 1.428, -2.412]} rotation={[Math.PI / 2, 0.271, -Math.PI / 2]} scale={1.552}>
          <group name="Neck_Taper" position={[-0.009, 0.041, -0.081]} scale={0.164} />
          <mesh name="Body_Bottom" geometry={nodes.Body_Bottom.geometry} material={materials.PaletteMaterial012} scale={0.353} />
          <mesh name="Body_Top" geometry={nodes.Body_Top.geometry} material={materials.PaletteMaterial012} position={[-0.001, 0.083, -0.017]} scale={0.353} />
          <mesh name="Body_Wall" geometry={nodes.Body_Wall.geometry} material={materials.PaletteMaterial012} position={[0, 0.041, 0]} scale={0.353} />
          <mesh name="Bridge" geometry={nodes.Bridge.geometry} material={materials.PaletteMaterial001} position={[-0.008, 0.088, 0.195]} scale={0.126} />
          <mesh name="Bridge_Pins" geometry={nodes.Bridge_Pins.geometry} material={materials.PaletteMaterial001} position={[-0.053, 0.089, 0.227]} scale={0.2} />
          <mesh name="Capston" geometry={nodes.Capston.geometry} material={materials.PaletteMaterial013} position={[-0.045, 0.092, -1.037]} scale={0.2}>
            <mesh name="Capston_Nuts" geometry={nodes.Capston_Nuts.geometry} material={materials.PaletteMaterial013} position={[0, 0.007, 0]} />
          </mesh>
          <mesh name="Frets" geometry={nodes.Frets.geometry} material={materials.PaletteMaterial001} position={[-0.005, 0.089, -0.448]} scale={0.714} />
          <mesh name="Headstock" geometry={nodes.Headstock.geometry} material={materials.PaletteMaterial012} position={[-0.008, 0.082, -1.085]} scale={0.353} />
          <mesh name="Neck" geometry={nodes.Neck.geometry} material={materials.PaletteMaterial014} position={[-0.004, 0.065, -0.539]} scale={0.353} />
          <mesh name="Nut" geometry={nodes.Nut.geometry} material={materials.PaletteMaterial001} position={[-0.009, 0.06, -0.951]} scale={[0.337, 0.515, 0.337]} />
          <mesh name="Position_Marker" geometry={nodes.Position_Marker.geometry} material={materials.PaletteMaterial001} position={[-0.005, 0.092, -0.261]} rotation={[-0.006, 0, 0]} scale={0.006} />
          <mesh name="Ring_1" geometry={nodes.Ring_1.geometry} material={materials.PaletteMaterial001} position={[-0.008, 0.088, -0.043]} scale={0.353} />
          <mesh name="Ring_2" geometry={nodes.Ring_2.geometry} material={materials.PaletteMaterial001} position={[-0.008, 0.088, -0.043]} scale={0.353} />
          <mesh name="Saddle" geometry={nodes.Saddle.geometry} material={materials.PaletteMaterial001} position={[-0.004, 0.095, 0.198]} />
          <mesh name="String_A" geometry={nodes.String_A.geometry} material={materials.PaletteMaterial013} position={[-0.03, 0.099, -0.368]} scale={0.353} />
          <mesh name="String_B" geometry={nodes.String_B.geometry} material={materials.PaletteMaterial013} position={[0.019, 0.099, -0.368]} scale={0.353} />
          <mesh name="String_D" geometry={nodes.String_D.geometry} material={materials.PaletteMaterial013} position={[-0.014, 0.099, -0.368]} scale={0.353} />
          <mesh name="String_E" geometry={nodes.String_E.geometry} material={materials.PaletteMaterial013} position={[-0.046, 0.099, -0.367]} scale={0.353} />
          <mesh name="String_e" geometry={nodes.String_e.geometry} material={materials.PaletteMaterial013} position={[0.034, 0.099, -0.368]} scale={0.353} />
          <mesh name="String_G" geometry={nodes.String_G.geometry} material={materials.PaletteMaterial013} position={[0.003, 0.099, -0.368]} scale={0.353} />
          <mesh name="Tunning_Plug_Holder" geometry={nodes.Tunning_Plug_Holder.geometry} material={materials.PaletteMaterial013} position={[-0.083, 0.082, -1.037]} scale={0.2}>
            <mesh name="Tunning_Plug_Nut" geometry={nodes.Tunning_Plug_Nut.geometry} material={materials.PaletteMaterial013} position={[0.056, 0, 0.001]} scale={0.079} />
          </mesh>
        </group>
        <mesh name="guitarHold" geometry={nodes.guitarHold.geometry} material={materials.Wood_stand} position={[-4.816, 0.831, -2.455]} rotation={[0, -0.114, -Math.PI / 2]} scale={0.114} />
        <group name="walls" position={[0, 0.517, 0]} scale={5.164}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials.Floor} />
          <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials.PaletteMaterial001} />
        </group>
        <group name="couch1" position={[3.746, 0.722, 2.594]} scale={[1, 1, 2.13]}>
          <mesh name="Plane015" geometry={nodes.Plane015.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane015_1" geometry={nodes.Plane015_1.geometry} material={materials.PaletteMaterial001} />
        </group>
        <mesh name="Shelf1" geometry={nodes.Shelf1.geometry} material={materials.PaletteMaterial001} position={[-4.714, 3.882, -4.163]} scale={[0.448, 1, 1]} />
        <mesh name="Shelf2" geometry={nodes.Shelf2.geometry} material={materials.PaletteMaterial001} position={[-4.156, 4.715, -4.61]} rotation={[0, 1.571, 0]} scale={[0.448, 1, 1]} />
        <group name="Pic" position={[-0.989, 4.193, -5.13]} rotation={[Math.PI / 2, 0, 0]} scale={[0.713, 0.97, 1.139]}>
          <mesh name="Plane027" geometry={nodes.Plane027.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane027_1" geometry={nodes.Plane027_1.geometry} material={materials.Pic3} />
        </group>
        <group name="Pic1" position={[1.403, 4.463, -5.13]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.713, 0.97, 1.139]}>
          <mesh name="Plane028" geometry={nodes.Plane028.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane028_1" geometry={nodes.Plane028_1.geometry} material={materials.Pic2} />
        </group>
        <group name="Pic2" position={[3.738, 4.193, -5.13]} rotation={[Math.PI / 2, 0, 0]} scale={[0.713, 0.97, 1.139]}>
          <mesh name="Plane029" geometry={nodes.Plane029.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane029_1" geometry={nodes.Plane029_1.geometry} material={materials.Pic1} />
        </group>
        <mesh name="bowl1" geometry={nodes.bowl1.geometry} material={materials.PaletteMaterial001} position={[4.283, 0.517, -2.138]} scale={0.27} />
        <mesh name="bowl" geometry={nodes.bowl.geometry} material={materials.PaletteMaterial001} position={[4.283, 0.517, -1.227]} scale={0.27} />
        <group name="TVdesk" position={[-4.154, 1.25, 1.549]} scale={[0.763, 1, 2.933]}>
          <mesh name="Plane022" geometry={nodes.Plane022.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane022_1" geometry={nodes.Plane022_1.geometry} material={materials.PaletteMaterial002} />
        </group>
        <group name="TV" position={[-4.904, 3.921, 1.267]} rotation={[0, 0, -Math.PI / 2]} scale={0.844}>
          <mesh name="Plane023" geometry={nodes.Plane023.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane023_1" geometry={nodes.Plane023_1.geometry} material={materials.TVdisplay} />
        </group>
        <group name="PlayStation" position={[-4.126, 1.77, 1.82]} scale={[0.543, 0.573, 0.745]}>
          <mesh name="Plane042" geometry={nodes.Plane042.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane042_1" geometry={nodes.Plane042_1.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane042_2" geometry={nodes.Plane042_2.geometry} material={materials.PaletteMaterial001} />
        </group>
        <mesh name="Speakers" geometry={nodes.Speakers.geometry} material={materials.PaletteMaterial001} position={[-5.175, 3.701, 4.319]} rotation={[0, 0, -Math.PI / 2]} scale={[1.55, 1, 0.135]} />
        <mesh name="legsPS" geometry={nodes.legsPS.geometry} material={materials.PaletteMaterial001} position={[-3.615, 0.516, 3.829]} scale={[0.157, 0.022, 0.157]} />
        <group name="PSController" position={[-3.728, 1.771, 3.215]} rotation={[-Math.PI / 2, 1.445, Math.PI / 2]} scale={0.137}>
          <mesh name="Plane043" geometry={nodes.Plane043.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane043_1" geometry={nodes.Plane043_1.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane043_2" geometry={nodes.Plane043_2.geometry} material={materials.Pad1} />
        </group>
        <mesh name="DeskDrawers" geometry={nodes.DeskDrawers.geometry} material={materials.PaletteMaterial001} position={[3.149, 2.087, -3.78]} scale={[0.545, 1, 1.088]}>
          <group name="Drawers" position={[-0.014, -0.558, 0.992]} rotation={[Math.PI / 2, 0, 0]} scale={[0.929, 0.233, 0.276]}>
            <mesh name="Plane049" geometry={nodes.Plane049.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Plane049_1" geometry={nodes.Plane049_1.geometry} material={materials.PaletteMaterial001} />
          </group>
        </mesh>
        <group name="Chair" position={[1.8, 1.563, -1.314]} rotation={[0, -0.835, 0]} scale={0.654}>
          <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane006_1" geometry={nodes.Plane006_1.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane006_2" geometry={nodes.Plane006_2.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane006_3" geometry={nodes.Plane006_3.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane006_4" geometry={nodes.Plane006_4.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane006_5" geometry={nodes.Plane006_5.geometry} material={materials.PaletteMaterial001} />
        </group>
        <group name="Desk" position={[0.81, 2.268, -3.783]} scale={[2.762, 1, 1.099]}>
          <mesh name="Plane021" geometry={nodes.Plane021.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane021_1" geometry={nodes.Plane021_1.geometry} material={materials.PaletteMaterial001} />
          <group name="Keyboard" position={[0.063, 0.215, 0.441]} rotation={[0.08, 0, 0]} scale={[0.329, 0.299, 0.231]}>
            <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Plane005_1" geometry={nodes.Plane005_1.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Plane005_2" geometry={nodes.Plane005_2.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Plane005_3" geometry={nodes.Plane005_3.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Monitor" position={[0.139, 1.092, 0.028]} rotation={[Math.PI / 2, 0, 0]} scale={[0.733, 0.487, 0.578]}>
            <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Plane004_1" geometry={nodes.Plane004_1.geometry} material={materials.MonitorDisplay0} />
            <mesh name="Plane004_2" geometry={nodes.Plane004_2.geometry} material={materials.MonitorDisplay1} />
            <mesh name="Plane004_3" geometry={nodes.Plane004_3.geometry} material={materials.PaletteMaterial001} />
          </group>
          <mesh name="Mouse" geometry={nodes.Mouse.geometry} material={materials.PaletteMaterial001} position={[0.619, 0.2, 0.546]} rotation={[0, 0.155, 0]} scale={[0.06, 0.16, 0.145]}>
            <mesh name="Mouse_pad" geometry={nodes.Mouse_pad.geometry} material={materials.Pad1} position={[-6.803, -0.073, -1.275]} rotation={[0, -0.109, 0]} scale={[10.163, 2.159, 3.541]} />
            <mesh name="Scroll" geometry={nodes.Scroll.geometry} material={materials.PaletteMaterial001} position={[0.203, 0.262, -0.604]} rotation={[-0.296, -0.089, -1.587]} scale={[-0.061, -0.061, -0.131]} />
          </mesh>
        </group>
        <group name="PC" position={[-1.438, 2.45, -3.706]} scale={[0.289, 0.831, 0.831]}>
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.PaletteMaterial003} />
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane001_2" geometry={nodes.Plane001_2.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane001_3" geometry={nodes.Plane001_3.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane001_4" geometry={nodes.Plane001_4.geometry} material={materials.PaletteMaterial004} />
        </group>
        <mesh name="legsDesk" geometry={nodes.legsDesk.geometry} material={materials.PaletteMaterial001} position={[-1.598, 0.527, -2.99]} scale={0.157} />
        <mesh name="legsDesk001" geometry={nodes.legsDesk001.geometry} material={materials.PaletteMaterial001} position={[3.179, 1.918, -2.99]} scale={[0.157, 0.019, 0.157]} />
        <group name="Eevee" position={[-4.511, 3.875, -2.774]} rotation={[0, Math.PI / 4, 0]} scale={0.017}>
          <mesh name="Eevee_1" geometry={nodes.Eevee_1.geometry} material={materials.Material__12} />
          <mesh name="Eevee_2" geometry={nodes.Eevee_2.geometry} material={materials.Material__13} />
          <mesh name="Eevee_3" geometry={nodes.Eevee_3.geometry} material={materials.Material__14} />
        </group>
        <group name="Football" position={[-4.252, 4.975, -4.587]} rotation={[Math.PI / 2, 0, 0]} scale={0.272}>
          <mesh name="Solid002" geometry={nodes.Solid002.geometry} material={materials.PaletteMaterial008} />
          <mesh name="Solid002_1" geometry={nodes.Solid002_1.geometry} material={materials.PaletteMaterial008} />
        </group>
        <mesh name="Cello_hold" geometry={nodes.Cello_hold.geometry} material={materials.PaletteMaterial001} position={[-4.171, 3.77, -3.373]} rotation={[0, 0, -Math.PI / 2]} scale={0.065}>
          <mesh name="Torus" geometry={nodes.Torus.geometry} material={materials.PaletteMaterial001} position={[-0.336, 1.722, 0.109]} rotation={[0, 0, Math.PI / 2]} scale={-1.047} />
        </mesh>
        <group name="NintendoSwitch" position={[-3.933, 1.791, 0.174]} rotation={[0, 0, Math.PI / 2]} scale={[0.151, 0.145, 0.252]}>
          <mesh name="Plane075" geometry={nodes.Plane075.geometry} material={materials.PaletteMaterial008} />
          <mesh name="Plane075_1" geometry={nodes.Plane075_1.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane075_2" geometry={nodes.Plane075_2.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane075_3" geometry={nodes.Plane075_3.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane075_4" geometry={nodes.Plane075_4.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane075_5" geometry={nodes.Plane075_5.geometry} material={materials.PaletteMaterial001} />
        </group>
        <group name="Coffee_Table001" position={[0.239, 0.518, 1.163]} scale={[0.737, 0.403, 0.04]}>
          <mesh name="Cube018" geometry={nodes.Cube018.geometry} material={materials.Floor} />
          <mesh name="Cube018_1" geometry={nodes.Cube018_1.geometry} material={materials.PaletteMaterial001} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/GamingJoin-transformed.glb')
