/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 GamingImpr.glb --transform --simplify 
Files: GamingImpr.glb [92.03MB] > GamingImpr-transformed.glb [2.15MB] (98%)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/GamingImpr-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Radiator_3x120_EKweb" position={[-1.52, 3.103, -3.041]} rotation={[Math.PI / 2, 0, 0]} scale={3.11}>
          <mesh name="BezierCurve001" geometry={nodes.BezierCurve001.geometry} material={materials.PaletteMaterial005} position={[0, 0, -0.063]} />
          <mesh name="BezierCurve004" geometry={nodes.BezierCurve004.geometry} material={materials.PaletteMaterial005} position={[0, 0, -0.063]} />
          <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials.PaletteMaterial001} position={[0, 0.038, -0.126]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.064, 0.064, 0.009]} />
          <group name="FAN_Blade" position={[0, 0.037, 0.123]}>
            <mesh name="Fan001" geometry={nodes.Fan001.geometry} material={materials.PaletteMaterial006} />
            <mesh name="Fan001_1" geometry={nodes.Fan001_1.geometry} material={materials.PaletteMaterial005} />
            <mesh name="Fan001_2" geometry={nodes.Fan001_2.geometry} material={materials.PaletteMaterial007} />
            <mesh name="Fan001_3" geometry={nodes.Fan001_3.geometry} material={materials.PaletteMaterial002} />
          </group>
          <group name="FAN_Blade002" position={[0, 0.037, 0]}>
            <mesh name="Fan001" geometry={nodes.Fan001.geometry} material={materials.PaletteMaterial006} />
            <mesh name="Fan001_1" geometry={nodes.Fan001_1.geometry} material={materials.PaletteMaterial005} />
            <mesh name="Fan001_2" geometry={nodes.Fan001_2.geometry} material={materials.PaletteMaterial007} />
            <mesh name="Fan001_3" geometry={nodes.Fan001_3.geometry} material={materials.PaletteMaterial002} />
          </group>
          <group name="FAN_Blade003" position={[0, 0.037, -0.124]}>
            <mesh name="Fan001" geometry={nodes.Fan001.geometry} material={materials.PaletteMaterial006} />
            <mesh name="Fan001_1" geometry={nodes.Fan001_1.geometry} material={materials.PaletteMaterial005} />
            <mesh name="Fan001_2" geometry={nodes.Fan001_2.geometry} material={materials.PaletteMaterial007} />
            <mesh name="Fan001_3" geometry={nodes.Fan001_3.geometry} material={materials.PaletteMaterial002} />
          </group>
          <mesh name="Fan_Housing003" geometry={nodes.Fan_Housing003.geometry} material={materials.PaletteMaterial002} />
        </group>
        <group name="E_Cello_feng_ling_MCP001" position={[-4.141, 1.081, -3.36]} rotation={[0, Math.PI / 2, 0]} scale={2.217}>
          <mesh name="Cello" geometry={nodes.Cello.geometry} material={materials['wood.1']} rotation={[Math.PI / 2, 0, 0]}>
            <mesh name="Britge" geometry={nodes.Britge.geometry} material={materials.PaletteMaterial009} position={[0, 0.078, -0.576]} />
            <mesh name="Circle019" geometry={nodes.Circle019.geometry} material={materials.PaletteMaterial001} position={[0, 0.023, -0.234]} />
            <mesh name="Circle021" geometry={nodes.Circle021.geometry} material={materials.PaletteMaterial010} position={[0, 0.029, -0.88]} />
            <mesh name="Circle022" geometry={nodes.Circle022.geometry} material={materials.PaletteMaterial001} position={[0.011, 0.094, -0.46]} />
            <mesh name="Circle023" geometry={nodes.Circle023.geometry} material={materials.PaletteMaterial001} position={[-0.011, 0.094, -0.46]} />
            <mesh name="Circle024" geometry={nodes.Circle024.geometry} material={materials.PaletteMaterial001} position={[-0.028, 0.088, -0.459]} />
            <mesh name="Circle029" geometry={nodes.Circle029.geometry} material={materials.PaletteMaterial001} position={[0.028, 0.088, -0.459]} />
            <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.PaletteMaterial010} position={[0, 0.029, -0.88]} />
            <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials.PaletteMaterial010} position={[0, 0.029, -0.88]} />
            <mesh name="Spiral" geometry={nodes.Spiral.geometry} material={materials['wood.1']} position={[0, 0.029, -0.88]} />
            <group name="Stachel" position={[0, 0, -0.207]} scale={0.015}>
              <mesh name="Cylinder015" geometry={nodes.Cylinder015.geometry} material={materials.PaletteMaterial010} />
              <mesh name="Cylinder015_1" geometry={nodes.Cylinder015_1.geometry} material={materials.PaletteMaterial001} />
              <mesh name="Cylinder015_2" geometry={nodes.Cylinder015_2.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="Wirbel" position={[0.047, 0.006, -1.37]} rotation={[0, 0, Math.PI / 2]}>
              <mesh name="Cylinder014" geometry={nodes.Cylinder014.geometry} material={materials.PaletteMaterial011} />
              <mesh name="Cylinder014_1" geometry={nodes.Cylinder014_1.geometry} material={materials.PaletteMaterial010} />
            </group>
            <group name="Wirbel001" position={[0.048, -0.013, -1.425]} rotation={[0, 0, Math.PI / 2]}>
              <mesh name="Cylinder013" geometry={nodes.Cylinder013.geometry} material={materials.PaletteMaterial011} />
              <mesh name="Cylinder013_1" geometry={nodes.Cylinder013_1.geometry} material={materials.PaletteMaterial010} />
            </group>
            <group name="Wirbel002" position={[-0.048, -0.004, -1.398]} rotation={[0, 0, Math.PI / 2]}>
              <mesh name="Cylinder012" geometry={nodes.Cylinder012.geometry} material={materials.PaletteMaterial011} />
              <mesh name="Cylinder012_1" geometry={nodes.Cylinder012_1.geometry} material={materials.PaletteMaterial010} />
            </group>
            <group name="Wirbel003" position={[-0.05, -0.022, -1.45]} rotation={[0, 0, Math.PI / 2]}>
              <mesh name="Cylinder011" geometry={nodes.Cylinder011.geometry} material={materials.PaletteMaterial011} />
              <mesh name="Cylinder011_1" geometry={nodes.Cylinder011_1.geometry} material={materials.PaletteMaterial010} />
            </group>
          </mesh>
        </group>
        <group name="Cast_Away_Volleyball" position={[-2.732, 4.711, -4.494]} rotation={[Math.PI, -0.698, Math.PI]} scale={2.567}>
          <mesh name="VolleyBallFinished" geometry={nodes.VolleyBallFinished.geometry} material={materials.VolleyBall} position={[0.18, 0.107, 0.151]}>
            <mesh name="InflationValave" geometry={nodes.InflationValave.geometry} material={materials.PaletteMaterial001} />
          </mesh>
        </group>
        <group name="Guitar_made_of_Bezier_curve" position={[-4.679, 1.428, -2.412]} rotation={[Math.PI / 2, 0.271, -Math.PI / 2]} scale={1.552}>
          <group name="Neck_Taper" position={[-0.009, 0.041, -0.081]} scale={0.164} />
          <mesh name="Body_Bottom" geometry={nodes.Body_Bottom.geometry} material={materials.PaletteMaterial012} scale={0.353} />
          <mesh name="Body_Top" geometry={nodes.Body_Top.geometry} material={materials.PaletteMaterial012} position={[-0.001, 0.083, -0.017]} scale={0.353} />
          <mesh name="Body_Wall" geometry={nodes.Body_Wall.geometry} material={materials.PaletteMaterial012} position={[0, 0.041, 0]} scale={0.353} />
          <mesh name="Bridge" geometry={nodes.Bridge.geometry} material={materials.PaletteMaterial001} position={[-0.008, 0.088, 0.195]} scale={0.126} />
          <mesh name="Bridge_Pins" geometry={nodes.Bridge_Pins.geometry} material={materials.PaletteMaterial001} position={[-0.053, 0.089, 0.227]} scale={0.2} />
          <mesh name="Capston" geometry={nodes.Capston.geometry} material={materials.PaletteMaterial013} position={[-0.045, 0.092, -1.037]} scale={0.2}>
            <mesh name="Capston_Nuts" geometry={nodes.Capston_Nuts.geometry} material={materials.PaletteMaterial013} position={[0, 0.007, 0]} />
          </mesh>
          <mesh name="Frets" geometry={nodes.Frets.geometry} material={materials.PaletteMaterial001} position={[-0.005, 0.089, -0.448]} scale={0.714} />
          <mesh name="Headstock" geometry={nodes.Headstock.geometry} material={materials.PaletteMaterial012} position={[-0.008, 0.082, -1.085]} scale={0.353} />
          <mesh name="Neck" geometry={nodes.Neck.geometry} material={materials.PaletteMaterial014} position={[-0.004, 0.065, -0.539]} scale={0.353} />
          <mesh name="Nut" geometry={nodes.Nut.geometry} material={materials.PaletteMaterial001} position={[-0.009, 0.06, -0.951]} scale={[0.337, 0.515, 0.337]} />
          <mesh name="Position_Marker" geometry={nodes.Position_Marker.geometry} material={materials.PaletteMaterial001} position={[-0.005, 0.092, -0.261]} rotation={[-0.006, 0, 0]} scale={0.006} />
          <mesh name="Ring_1" geometry={nodes.Ring_1.geometry} material={materials.PaletteMaterial001} position={[-0.008, 0.088, -0.043]} scale={0.353} />
          <mesh name="Ring_2" geometry={nodes.Ring_2.geometry} material={materials.PaletteMaterial001} position={[-0.008, 0.088, -0.043]} scale={0.353} />
          <mesh name="Saddle" geometry={nodes.Saddle.geometry} material={materials.PaletteMaterial001} position={[-0.004, 0.095, 0.198]} />
          <mesh name="String_A" geometry={nodes.String_A.geometry} material={materials.PaletteMaterial013} position={[-0.03, 0.099, -0.368]} scale={0.353} />
          <mesh name="String_B" geometry={nodes.String_B.geometry} material={materials.PaletteMaterial013} position={[0.019, 0.099, -0.368]} scale={0.353} />
          <mesh name="String_D" geometry={nodes.String_D.geometry} material={materials.PaletteMaterial013} position={[-0.014, 0.099, -0.368]} scale={0.353} />
          <mesh name="String_E" geometry={nodes.String_E.geometry} material={materials.PaletteMaterial013} position={[-0.046, 0.099, -0.367]} scale={0.353} />
          <mesh name="String_e" geometry={nodes.String_e.geometry} material={materials.PaletteMaterial013} position={[0.034, 0.099, -0.368]} scale={0.353} />
          <mesh name="String_G" geometry={nodes.String_G.geometry} material={materials.PaletteMaterial013} position={[0.003, 0.099, -0.368]} scale={0.353} />
          <mesh name="Tunning_Plug_Holder" geometry={nodes.Tunning_Plug_Holder.geometry} material={materials.PaletteMaterial013} position={[-0.083, 0.082, -1.037]} scale={0.2}>
            <mesh name="Tunning_Plug_Nut" geometry={nodes.Tunning_Plug_Nut.geometry} material={materials.PaletteMaterial013} position={[0.056, 0, 0.001]} scale={0.079} />
          </mesh>
        </group>
        <mesh name="Plane025" geometry={nodes.Plane025.geometry} material={materials.Wood_stand} position={[-4.816, 0.831, -2.455]} rotation={[0, -0.114, -Math.PI / 2]} scale={0.114} />
        <group name="walls" position={[0, 0.517, 0]} scale={5.164}>
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials.Floor} />
          <mesh name="Plane_3" geometry={nodes.Plane_3.geometry} material={materials.PaletteMaterial001} />
        </group>
        <mesh name="couch1" geometry={nodes.couch1.geometry} material={materials.PaletteMaterial001} position={[3.746, 0.722, 2.594]} scale={[1, 1, 2.13]}>
          <mesh name="CLegs" geometry={nodes.CLegs.geometry} material={materials.PaletteMaterial001} position={[0.389, -0.71, -2.306]} scale={[1, 1, 0.469]} />
          <mesh name="CLegs1" geometry={nodes.CLegs1.geometry} material={materials.PaletteMaterial001} position={[-6.08, -0.71, -1.646]} rotation={[0, 1.571, 0]} scale={[0.469, 1, 1]} />
          <mesh name="couch1001" geometry={nodes.couch1001.geometry} material={materials.PaletteMaterial001} position={[-3.118, 0, 0.548]} rotation={[0, -1.571, 0]} scale={[0.469, 1, 2.13]} />
          <mesh name="Cushin" geometry={nodes.Cushin.geometry} material={materials.PaletteMaterial001} position={[-0.088, 1.045, -1.012]} scale={[1.056, 1.056, 0.495]} />
          <mesh name="Cushin1" geometry={nodes.Cushin1.geometry} material={materials.PaletteMaterial001} position={[-4.907, 1.033, 0.425]} rotation={[0, 1.571, 0]} scale={[0.513, 1.093, 1.093]} />
          <mesh name="cushins" geometry={nodes.cushins.geometry} material={materials.PaletteMaterial001} position={[-2.075, 0.47, 0.463]} scale={[0.858, 0.908, 0.403]} />
          <mesh name="cushins001" geometry={nodes.cushins001.geometry} material={materials.PaletteMaterial001} position={[-4.126, 0.47, 0.463]} scale={[0.858, 0.908, 0.403]} />
          <mesh name="cushins002" geometry={nodes.cushins002.geometry} material={materials.PaletteMaterial001} position={[-2.075, 1.263, 1.012]} rotation={[-1.492, 0, 0]} scale={[0.858, 0.429, 0.857]} />
          <mesh name="cushins003" geometry={nodes.cushins003.geometry} material={materials.PaletteMaterial001} position={[-4.126, 1.263, 1.012]} rotation={[-1.492, 0, 0]} scale={[0.858, 0.429, 0.857]} />
          <mesh name="cushins004" geometry={nodes.cushins004.geometry} material={materials.PaletteMaterial001} position={[-0.181, 0.47, -0.606]} rotation={[0, 1.571, 0]} scale={[0.403, 0.908, 0.858]} />
          <mesh name="cushins005" geometry={nodes.cushins005.geometry} material={materials.PaletteMaterial001} position={[-0.181, 0.47, 0.357]} rotation={[0, 1.571, 0]} scale={[0.403, 0.908, 0.858]} />
          <mesh name="cushins006" geometry={nodes.cushins006.geometry} material={materials.PaletteMaterial001} position={[0.989, 1.263, -0.606]} rotation={[-Math.PI / 2, 0.06, Math.PI / 2]} scale={[0.403, 0.908, 0.858]} />
          <mesh name="cushins007" geometry={nodes.cushins007.geometry} material={materials.PaletteMaterial001} position={[0.989, 1.263, 0.357]} rotation={[-Math.PI / 2, 0.06, Math.PI / 2]} scale={[0.403, 0.908, 0.858]} />
          <mesh name="cushins008" geometry={nodes.cushins008.geometry} material={materials.PaletteMaterial001} position={[-0.064, 1.263, 1.012]} rotation={[-1.492, 0, 0]} scale={[0.815, 0.429, 0.857]} />
        </mesh>
        <mesh name="Shelf1" geometry={nodes.Shelf1.geometry} material={materials.PaletteMaterial001} position={[-4.714, 3.882, -4.163]} scale={[0.448, 1, 1]} />
        <mesh name="Shelf2" geometry={nodes.Shelf2.geometry} material={materials.PaletteMaterial001} position={[-4.156, 4.715, -4.61]} rotation={[0, 1.571, 0]} scale={[0.448, 1, 1]} />
        <group name="Pic" position={[-0.989, 4.193, -5.13]} rotation={[Math.PI / 2, 0, 0]} scale={[0.713, 0.97, 1.139]}>
          <mesh name="Plane027" geometry={nodes.Plane027.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane027_1" geometry={nodes.Plane027_1.geometry} material={materials.Pic3} />
        </group>
        <group name="Pic1" position={[1.403, 4.463, -5.13]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.713, 0.97, 1.139]}>
          <mesh name="Plane028" geometry={nodes.Plane028.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane028_1" geometry={nodes.Plane028_1.geometry} material={materials.Pic2} />
        </group>
        <group name="Pic2" position={[3.738, 4.193, -5.13]} rotation={[Math.PI / 2, 0, 0]} scale={[0.713, 0.97, 1.139]}>
          <mesh name="Plane029" geometry={nodes.Plane029.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane029_1" geometry={nodes.Plane029_1.geometry} material={materials.Pic1} />
        </group>
        <mesh name="bowl1" geometry={nodes.bowl1.geometry} material={materials.PaletteMaterial001} position={[4.283, 0.517, -2.138]} scale={0.27} />
        <mesh name="bowl" geometry={nodes.bowl.geometry} material={materials.PaletteMaterial001} position={[4.283, 0.517, -1.227]} scale={0.27} />
        <group name="TVdesk" position={[-4.154, 1.25, 1.549]} scale={[0.763, 1, 2.933]}>
          <mesh name="Plane022" geometry={nodes.Plane022.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane022_1" geometry={nodes.Plane022_1.geometry} material={materials.PaletteMaterial002} />
        </group>
        <group name="TV" position={[-4.904, 3.921, 1.267]} rotation={[0, 0, -Math.PI / 2]} scale={0.844}>
          <mesh name="Plane023" geometry={nodes.Plane023.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane023_1" geometry={nodes.Plane023_1.geometry} material={materials.TVdisplay} />
        </group>
        <mesh name="PlayStation" geometry={nodes.PlayStation.geometry} material={materials.PaletteMaterial001} position={[-4.126, 1.77, 1.82]} scale={[0.543, 0.573, 0.745]}>
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.PaletteMaterial001} scale={[0.97, 0.919, 0.963]} />
          <group name="Plane002" scale={0.919}>
            <mesh name="Plane041" geometry={nodes.Plane041.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Plane041_1" geometry={nodes.Plane041_1.geometry} material={materials.PaletteMaterial001} />
          </group>
        </mesh>
        <mesh name="Speakers" geometry={nodes.Speakers.geometry} material={materials.PaletteMaterial001} position={[-5.175, 3.701, 4.319]} rotation={[0, 0, -Math.PI / 2]} scale={[1.55, 1, 0.135]} />
        <mesh name="legsPS" geometry={nodes.legsPS.geometry} material={materials.PaletteMaterial001} position={[-3.615, 0.516, 3.829]} scale={[0.157, 0.022, 0.157]} />
        <mesh name="PSController" geometry={nodes.PSController.geometry} material={materials.PaletteMaterial001} position={[-4.258, 1.881, 3.584]} rotation={[Math.PI / 2, 0.962, -Math.PI / 2]} scale={0.137}>
          <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials.PaletteMaterial001} position={[-0.549, 0.634, -0.023]} rotation={[0.14, 0, 0]} scale={0.216} />
          <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={materials.Pad1} position={[0.862, 0.651, -0.29]} scale={0.096} />
          <mesh name="Circle002" geometry={nodes.Circle002.geometry} material={materials.Pad1} position={[0.862, 0.619, -0.644]} rotation={[-0.083, 0, 0]} scale={0.096} />
          <mesh name="Circle003" geometry={nodes.Circle003.geometry} material={materials.Pad1} position={[1.039, 0.634, -0.474]} rotation={[2.27, 1.517, -2.357]} scale={0.096} />
          <mesh name="Circle004" geometry={nodes.Circle004.geometry} material={materials.Pad1} position={[0.685, 0.651, -0.461]} rotation={[2.481, 1.525, -2.53]} scale={0.096} />
          <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials.PaletteMaterial001} position={[-0.786, 0.289, -1.025]} rotation={[1.559, 0.013, 2.828]} scale={0.124} />
          <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials.PaletteMaterial001} position={[-1.192, 0.637, -0.49]} rotation={[0, 0, 0.04]} scale={0.06} />
          <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials.PaletteMaterial001} position={[-0.584, 0.648, -0.49]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.06} />
          <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials.PaletteMaterial001} position={[-0.889, 0.622, -0.813]} rotation={[-0.128, -Math.PI / 2, 0]} scale={0.06} />
          <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials.PaletteMaterial001} position={[-0.884, 0.648, -0.16]} rotation={[0, 1.571, 0]} scale={0.06} />
          <mesh name="Plane008" geometry={nodes.Plane008.geometry} material={materials.PaletteMaterial001} position={[-0.765, 0.488, -0.947]} rotation={[-0.056, -1.323, -1.908]} scale={[0.069, 0.127, 0.175]} />
          <mesh name="Plane009" geometry={nodes.Plane009.geometry} material={materials.PaletteMaterial001} position={[-0.061, 0.649, -0.652]} rotation={[1.504, -1.567, 1.638]} scale={0.362} />
        </mesh>
        <mesh name="PSController001" geometry={nodes.PSController001.geometry} material={materials.PaletteMaterial001} position={[-3.765, 1.882, 3.584]} rotation={[Math.PI / 2, 0.962, -Math.PI / 2]} scale={0.137}>
          <mesh name="Circle005" geometry={nodes.Circle005.geometry} material={materials.PaletteMaterial001} position={[-0.549, 0.634, -0.023]} rotation={[0.14, 0, 0]} scale={0.216} />
          <mesh name="Circle006" geometry={nodes.Circle006.geometry} material={materials.Pad1} position={[0.862, 0.651, -0.29]} scale={0.096} />
          <mesh name="Circle007" geometry={nodes.Circle007.geometry} material={materials.Pad1} position={[0.862, 0.619, -0.644]} rotation={[-0.083, 0, 0]} scale={0.096} />
          <mesh name="Circle008" geometry={nodes.Circle008.geometry} material={materials.Pad1} position={[1.039, 0.634, -0.474]} rotation={[2.27, 1.517, -2.357]} scale={0.096} />
          <mesh name="Circle009" geometry={nodes.Circle009.geometry} material={materials.Pad1} position={[0.685, 0.651, -0.461]} rotation={[2.481, 1.525, -2.53]} scale={0.096} />
          <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials.PaletteMaterial001} position={[-1.192, 0.637, -0.49]} rotation={[0, 0, 0.04]} scale={0.06} />
          <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials.PaletteMaterial001} position={[-0.584, 0.648, -0.49]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.06} />
          <mesh name="Plane012" geometry={nodes.Plane012.geometry} material={materials.PaletteMaterial001} position={[-0.889, 0.622, -0.813]} rotation={[-0.128, -Math.PI / 2, 0]} scale={0.06} />
          <mesh name="Plane013" geometry={nodes.Plane013.geometry} material={materials.PaletteMaterial001} position={[-0.884, 0.648, -0.16]} rotation={[0, 1.571, 0]} scale={0.06} />
          <mesh name="Plane014" geometry={nodes.Plane014.geometry} material={materials.PaletteMaterial001} position={[-0.061, 0.649, -0.652]} rotation={[1.504, -1.567, 1.638]} scale={0.362} />
          <mesh name="Plane016" geometry={nodes.Plane016.geometry} material={materials.PaletteMaterial001} position={[-0.786, 0.289, -1.025]} rotation={[1.559, 0.013, 2.828]} scale={0.124} />
          <mesh name="Plane017" geometry={nodes.Plane017.geometry} material={materials.PaletteMaterial001} position={[-0.765, 0.488, -0.947]} rotation={[-0.056, -1.323, -1.908]} scale={[0.069, 0.127, 0.175]} />
        </mesh>
        <mesh name="Plane015" geometry={nodes.Plane015.geometry} material={materials.PaletteMaterial001} position={[-4.028, 1.857, 3.594]} scale={[0.546, 0.216, 0.036]} />
        <mesh name="DeskDrawers" geometry={nodes.DeskDrawers.geometry} material={materials.PaletteMaterial001} position={[3.149, 2.087, -3.78]} scale={[0.545, 1, 1.088]}>
          <group name="Drawers" position={[-0.014, -0.558, 0.992]} rotation={[Math.PI / 2, 0, 0]} scale={[0.929, 0.233, 0.276]}>
            <mesh name="Plane049" geometry={nodes.Plane049.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Plane049_1" geometry={nodes.Plane049_1.geometry} material={materials.PaletteMaterial001} />
          </group>
        </mesh>
        <group name="Chair" position={[1.8, 1.563, -1.314]} rotation={[0, -0.835, 0]} scale={0.654}>
          <mesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Mesh_2" geometry={nodes.Mesh_2.geometry} material={materials.PaletteMaterial001} />
          <group name="ChairBack" position={[-0.019, 1.654, 1.252]} rotation={[-1.314, -0.005, 0.013]} scale={[0.655, 0.904, 1.562]}>
            <mesh name="Mesh_8" geometry={nodes.Mesh_8.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Mesh_9" geometry={nodes.Mesh_9.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.PaletteMaterial001} position={[0.027, 0.258, 0.852]} rotation={[1.201, -0.017, -0.01]} scale={[1.031, 0.271, 0.184]} />
          </group>
          <group name="HandCushim" position={[1.114, 0.771, -0.143]} rotation={[0.129, 0, 0]} scale={[0.125, 1, 0.812]}>
            <mesh name="Plane038" geometry={nodes.Plane038.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Plane038_1" geometry={nodes.Plane038_1.geometry} material={materials.PaletteMaterial001} />
          </group>
          <mesh name="HHolder" geometry={nodes.HHolder.geometry} material={materials.PaletteMaterial001} position={[1.118, 0.09, 0.165]} scale={[0.155, 0.906, 0.906]} />
          <mesh name="LegHolder" geometry={nodes.LegHolder.geometry} material={materials.PaletteMaterial001} position={[-0.014, 0.087, 0.406]} scale={0.274}>
            <mesh name="Leg" geometry={nodes.Leg.geometry} material={materials.PaletteMaterial001} position={[-0.026, -4.44, -0.026]} rotation={[Math.PI / 2, 0, -0.629]} scale={[0.297, 0.549, 0.615]}>
              <mesh name="wheel" geometry={nodes.wheel.geometry} material={materials.PaletteMaterial001} position={[-0.004, -11.031, 2.123]} rotation={[0, 0, -Math.PI / 2]} scale={[0.711, 0.781, 0.634]} />
              <mesh name="WheelCover" geometry={nodes.WheelCover.geometry} material={materials.PaletteMaterial001} position={[-0.004, -11.031, 2.23]} rotation={[0, 0, -Math.PI / 2]} scale={[0.711, 1.017, 0.634]} />
            </mesh>
            <mesh name="Leg001" geometry={nodes.Leg001.geometry} material={materials.PaletteMaterial001} position={[-0.026, -4.44, -0.026]} rotation={[Math.PI / 2, 0, 0.942]} scale={[0.297, 0.549, 0.615]}>
              <mesh name="wheel001" geometry={nodes.wheel001.geometry} material={materials.PaletteMaterial001} position={[-0.004, -11.031, 2.123]} rotation={[0, 0, -Math.PI / 2]} scale={[0.711, 0.781, 0.634]} />
              <mesh name="WheelCover001" geometry={nodes.WheelCover001.geometry} material={materials.PaletteMaterial001} position={[-0.004, -11.031, 2.23]} rotation={[0, 0, -Math.PI / 2]} scale={[0.711, 1.017, 0.634]} />
            </mesh>
            <mesh name="Leg002" geometry={nodes.Leg002.geometry} material={materials.PaletteMaterial001} position={[-0.026, -4.44, -0.026]} rotation={[Math.PI / 2, 0, 2.513]} scale={[0.297, 0.549, 0.615]}>
              <mesh name="wheel002" geometry={nodes.wheel002.geometry} material={materials.PaletteMaterial001} position={[-0.004, -11.031, 2.123]} rotation={[0, 0, -Math.PI / 2]} scale={[0.711, 0.781, 0.634]} />
              <mesh name="WheelCover002" geometry={nodes.WheelCover002.geometry} material={materials.PaletteMaterial001} position={[-0.004, -11.031, 2.23]} rotation={[0, 0, -Math.PI / 2]} scale={[0.711, 1.017, 0.634]} />
            </mesh>
            <mesh name="Leg003" geometry={nodes.Leg003.geometry} material={materials.PaletteMaterial001} position={[-0.026, -4.44, -0.026]} rotation={[Math.PI / 2, 0, -2.2]} scale={[0.297, 0.549, 0.615]}>
              <mesh name="wheel003" geometry={nodes.wheel003.geometry} material={materials.PaletteMaterial001} position={[-0.005, -11.031, 2.123]} rotation={[0, 0, -Math.PI / 2]} scale={[0.711, 0.781, 0.634]} />
              <mesh name="WheelCover003" geometry={nodes.WheelCover003.geometry} material={materials.PaletteMaterial001} position={[-0.005, -11.031, 2.23]} rotation={[0, 0, -Math.PI / 2]} scale={[0.711, 1.017, 0.634]} />
            </mesh>
          </mesh>
        </group>
        <group name="Desk" position={[0.81, 2.268, -3.783]} scale={[2.762, 1, 1.099]}>
          <mesh name="Plane021" geometry={nodes.Plane021.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane021_1" geometry={nodes.Plane021_1.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Keyboard" geometry={nodes.Keyboard.geometry} material={materials.PaletteMaterial001} position={[0.063, 0.215, 0.441]} rotation={[0.08, 0, 0]} scale={[0.329, 0.299, 0.231]}>
            <mesh name="key" geometry={nodes.key.geometry} material={materials.PaletteMaterial001} position={[-0.82, 0, -0.588]} scale={[1.315, 4, 4.707]} />
            <mesh name="key001" geometry={nodes.key001.geometry} material={materials.PaletteMaterial001} position={[-0.724, 0, -0.588]} scale={[1.315, 4, 4.707]} />
            <mesh name="key002" geometry={nodes.key002.geometry} material={materials.PaletteMaterial001} position={[-0.628, 0, -0.588]} scale={[1.315, 4, 4.707]} />
            <mesh name="key003" geometry={nodes.key003.geometry} material={materials.PaletteMaterial001} position={[-0.533, 0, -0.588]} scale={[1.315, 4, 4.707]} />
            <mesh name="key004" geometry={nodes.key004.geometry} material={materials.PaletteMaterial001} position={[-0.437, 0, -0.588]} scale={[1.315, 4, 4.707]} />
            <mesh name="key005" geometry={nodes.key005.geometry} material={materials.PaletteMaterial001} position={[-0.341, 0, -0.588]} scale={[1.315, 4, 4.707]} />
            <mesh name="key006" geometry={nodes.key006.geometry} material={materials.PaletteMaterial001} position={[-0.246, 0, -0.588]} scale={[1.315, 4, 4.707]} />
            <mesh name="key007" geometry={nodes.key007.geometry} material={materials.PaletteMaterial001} position={[-0.15, 0, -0.588]} scale={[1.315, 4, 4.707]} />
            <mesh name="key008" geometry={nodes.key008.geometry} material={materials.PaletteMaterial001} position={[-0.054, 0, -0.588]} scale={[1.315, 4, 4.707]} />
            <mesh name="key009" geometry={nodes.key009.geometry} material={materials.PaletteMaterial001} position={[0.041, 0, -0.588]} scale={[1.315, 4, 4.707]} />
            <mesh name="key010" geometry={nodes.key010.geometry} material={materials.PaletteMaterial001} position={[0.137, 0, -0.588]} scale={[1.315, 4, 4.707]} />
            <mesh name="key011" geometry={nodes.key011.geometry} material={materials.PaletteMaterial001} position={[0.233, 0, -0.588]} scale={[1.315, 4, 4.707]} />
            <mesh name="key012" geometry={nodes.key012.geometry} material={materials.PaletteMaterial001} position={[-0.773, 0, -0.257]} scale={[1.315, 4, 4.707]} />
            <mesh name="key013" geometry={nodes.key013.geometry} material={materials.PaletteMaterial001} position={[-0.678, 0, -0.257]} scale={[1.315, 4, 4.707]} />
            <mesh name="key014" geometry={nodes.key014.geometry} material={materials.PaletteMaterial001} position={[-0.582, 0, -0.257]} scale={[1.315, 4, 4.707]} />
            <mesh name="key015" geometry={nodes.key015.geometry} material={materials.PaletteMaterial001} position={[-0.486, 0, -0.257]} scale={[1.315, 4, 4.707]} />
            <mesh name="key016" geometry={nodes.key016.geometry} material={materials.PaletteMaterial001} position={[-0.391, 0, -0.257]} scale={[1.315, 4, 4.707]} />
            <mesh name="key017" geometry={nodes.key017.geometry} material={materials.PaletteMaterial001} position={[-0.295, 0, -0.257]} scale={[1.315, 4, 4.707]} />
            <mesh name="key018" geometry={nodes.key018.geometry} material={materials.PaletteMaterial001} position={[-0.199, 0, -0.257]} scale={[1.315, 4, 4.707]} />
            <mesh name="key019" geometry={nodes.key019.geometry} material={materials.PaletteMaterial001} position={[-0.104, 0, -0.257]} scale={[1.315, 4, 4.707]} />
            <mesh name="key020" geometry={nodes.key020.geometry} material={materials.PaletteMaterial001} position={[-0.008, 0, -0.257]} scale={[1.315, 4, 4.707]} />
            <mesh name="key021" geometry={nodes.key021.geometry} material={materials.PaletteMaterial001} position={[0.088, 0, -0.257]} scale={[1.315, 4, 4.707]} />
            <mesh name="key022" geometry={nodes.key022.geometry} material={materials.PaletteMaterial001} position={[0.183, 0, -0.257]} scale={[1.315, 4, 4.707]} />
            <mesh name="key023" geometry={nodes.key023.geometry} material={materials.PaletteMaterial001} position={[0.279, 0, -0.257]} scale={[1.315, 4, 4.707]} />
            <mesh name="key024" geometry={nodes.key024.geometry} material={materials.PaletteMaterial001} position={[-0.746, 0, 0.08]} scale={[1.315, 4, 4.707]} />
            <mesh name="key025" geometry={nodes.key025.geometry} material={materials.PaletteMaterial001} position={[-0.651, 0, 0.08]} scale={[1.315, 4, 4.707]} />
            <mesh name="key026" geometry={nodes.key026.geometry} material={materials.PaletteMaterial001} position={[-0.555, 0, 0.08]} scale={[1.315, 4, 4.707]} />
            <mesh name="key027" geometry={nodes.key027.geometry} material={materials.PaletteMaterial001} position={[-0.459, 0, 0.08]} scale={[1.315, 4, 4.707]} />
            <mesh name="key028" geometry={nodes.key028.geometry} material={materials.PaletteMaterial001} position={[-0.364, 0, 0.08]} scale={[1.315, 4, 4.707]} />
            <mesh name="key029" geometry={nodes.key029.geometry} material={materials.PaletteMaterial001} position={[-0.268, 0, 0.08]} scale={[1.315, 4, 4.707]} />
            <mesh name="key030" geometry={nodes.key030.geometry} material={materials.PaletteMaterial001} position={[-0.172, 0, 0.08]} scale={[1.315, 4, 4.707]} />
            <mesh name="key031" geometry={nodes.key031.geometry} material={materials.PaletteMaterial001} position={[-0.077, 0, 0.08]} scale={[1.315, 4, 4.707]} />
            <mesh name="key032" geometry={nodes.key032.geometry} material={materials.PaletteMaterial001} position={[0.019, 0, 0.08]} scale={[1.315, 4, 4.707]} />
            <mesh name="key033" geometry={nodes.key033.geometry} material={materials.PaletteMaterial001} position={[0.115, 0, 0.08]} scale={[1.315, 4, 4.707]} />
            <mesh name="key034" geometry={nodes.key034.geometry} material={materials.PaletteMaterial001} position={[0.21, 0, 0.08]} scale={[1.315, 4, 4.707]} />
            <mesh name="key035" geometry={nodes.key035.geometry} material={materials.PaletteMaterial001} position={[0.306, 0, 0.08]} scale={[1.315, 4, 4.707]} />
            <mesh name="key036" geometry={nodes.key036.geometry} material={materials.PaletteMaterial001} position={[-0.705, 0, 0.416]} scale={[1.315, 4, 4.707]} />
            <mesh name="key037" geometry={nodes.key037.geometry} material={materials.PaletteMaterial001} position={[-0.609, 0, 0.416]} scale={[1.315, 4, 4.707]} />
            <mesh name="key038" geometry={nodes.key038.geometry} material={materials.PaletteMaterial001} position={[-0.514, 0, 0.416]} scale={[1.315, 4, 4.707]} />
            <mesh name="key039" geometry={nodes.key039.geometry} material={materials.PaletteMaterial001} position={[-0.418, 0, 0.416]} scale={[1.315, 4, 4.707]} />
            <mesh name="key040" geometry={nodes.key040.geometry} material={materials.PaletteMaterial001} position={[-0.322, 0, 0.416]} scale={[1.315, 4, 4.707]} />
            <mesh name="key041" geometry={nodes.key041.geometry} material={materials.PaletteMaterial001} position={[-0.227, 0, 0.416]} scale={[1.315, 4, 4.707]} />
            <mesh name="key042" geometry={nodes.key042.geometry} material={materials.PaletteMaterial001} position={[-0.131, 0, 0.416]} scale={[1.315, 4, 4.707]} />
            <mesh name="key043" geometry={nodes.key043.geometry} material={materials.PaletteMaterial001} position={[-0.035, 0, 0.416]} scale={[1.315, 4, 4.707]} />
            <mesh name="key044" geometry={nodes.key044.geometry} material={materials.PaletteMaterial001} position={[0.061, 0, 0.416]} scale={[1.315, 4, 4.707]} />
            <mesh name="key045" geometry={nodes.key045.geometry} material={materials.PaletteMaterial001} position={[0.156, 0, 0.416]} scale={[1.315, 4, 4.707]} />
            <mesh name="key046" geometry={nodes.key046.geometry} material={materials.PaletteMaterial001} position={[-0.901, 0, 0.759]} scale={[1.51, 4, 4.707]} />
            <mesh name="key047" geometry={nodes.key047.geometry} material={materials.PaletteMaterial001} position={[-0.801, 0, 0.759]} scale={[1.315, 4, 4.707]} />
            <mesh name="key048" geometry={nodes.key048.geometry} material={materials.PaletteMaterial001} position={[-0.705, 0, 0.759]} scale={[1.315, 4, 4.707]} />
            <mesh name="key049" geometry={nodes.key049.geometry} material={materials.PaletteMaterial001} position={[-0.609, 0, 0.759]} scale={[1.315, 4, 4.707]} />
            <mesh name="key050" geometry={nodes.key050.geometry} material={materials.PaletteMaterial001} position={[-0.892, 0, 0.416]} scale={[1.71, 4, 4.707]} />
            <mesh name="key051" geometry={nodes.key051.geometry} material={materials.PaletteMaterial001} position={[-0.791, 0, 0.416]} scale={[1.043, 4, 4.707]} />
            <mesh name="key052" geometry={nodes.key052.geometry} material={materials.PaletteMaterial001} position={[-0.876, 0, 0.08]} scale={[2.252, 4, 4.707]} />
            <mesh name="key053" geometry={nodes.key053.geometry} material={materials.PaletteMaterial001} position={[-0.888, 0, -0.257]} scale={[1.858, 4, 4.707]} />
            <mesh name="key054" geometry={nodes.key054.geometry} material={materials.PaletteMaterial001} position={[-0.911, 0, -0.588]} scale={[1.166, 4, 4.707]} />
            <mesh name="key055" geometry={nodes.key055.geometry} material={materials.PaletteMaterial001} position={[0.37, 0, -0.588]} scale={[2.34, 4, 4.707]} />
            <mesh name="key056" geometry={nodes.key056.geometry} material={materials.PaletteMaterial001} position={[0.403, 0, -0.257]} scale={[1.324, 4, 4.707]} />
            <mesh name="key057" geometry={nodes.key057.geometry} material={materials.PaletteMaterial001} position={[0.335, 0, 0.416]} scale={[3.418, 4, 4.707]} />
            <mesh name="key058" geometry={nodes.key058.geometry} material={materials.PaletteMaterial001} position={[-0.514, 0, 0.759]} scale={[1.315, 4, 4.707]} />
            <mesh name="key059" geometry={nodes.key059.geometry} material={materials.PaletteMaterial001} position={[-0.006, 0, 0.762]} scale={[1.315, 4, 4.707]} />
            <mesh name="key060" geometry={nodes.key060.geometry} material={materials.PaletteMaterial001} position={[0.094, 0, 0.762]} scale={[1.315, 4, 4.707]} />
            <mesh name="key061" geometry={nodes.key061.geometry} material={materials.PaletteMaterial001} position={[0.194, 0, 0.762]} scale={[1.315, 4, 4.707]} />
            <mesh name="key062" geometry={nodes.key062.geometry} material={materials.PaletteMaterial001} position={[0.299, 0, 0.762]} scale={[1.315, 4, 4.707]} />
            <mesh name="key063" geometry={nodes.key063.geometry} material={materials.PaletteMaterial001} position={[0.299, 0, 0.925]} scale={[1.315, 4, 4.707]} />
            <mesh name="key064" geometry={nodes.key064.geometry} material={materials.PaletteMaterial001} position={[0.404, 0, 0.762]} scale={[1.315, 4, 4.707]} />
            <mesh name="key065" geometry={nodes.key065.geometry} material={materials.PaletteMaterial001} position={[-0.91, 0.003, -0.876]} scale={[1.208, 4, 2.143]} />
            <mesh name="key066" geometry={nodes.key066.geometry} material={materials.PaletteMaterial001} position={[-0.823, 0.003, -0.876]} scale={[1.208, 4, 2.143]} />
            <mesh name="key067" geometry={nodes.key067.geometry} material={materials.PaletteMaterial001} position={[-0.735, 0.003, -0.876]} scale={[1.208, 4, 2.143]} />
            <mesh name="key068" geometry={nodes.key068.geometry} material={materials.PaletteMaterial001} position={[-0.648, 0.003, -0.876]} scale={[1.208, 4, 2.143]} />
            <mesh name="key069" geometry={nodes.key069.geometry} material={materials.PaletteMaterial001} position={[-0.56, 0.003, -0.876]} scale={[1.208, 4, 2.143]} />
            <mesh name="key070" geometry={nodes.key070.geometry} material={materials.PaletteMaterial001} position={[-0.473, 0.003, -0.876]} scale={[1.208, 4, 2.143]} />
            <mesh name="key071" geometry={nodes.key071.geometry} material={materials.PaletteMaterial001} position={[-0.385, 0.003, -0.876]} scale={[1.208, 4, 2.143]} />
            <mesh name="key072" geometry={nodes.key072.geometry} material={materials.PaletteMaterial001} position={[-0.298, 0.003, -0.876]} scale={[1.208, 4, 2.143]} />
            <mesh name="key073" geometry={nodes.key073.geometry} material={materials.PaletteMaterial001} position={[-0.211, 0.003, -0.876]} scale={[1.208, 4, 2.143]} />
            <mesh name="key074" geometry={nodes.key074.geometry} material={materials.PaletteMaterial001} position={[-0.123, 0.003, -0.876]} scale={[1.208, 4, 2.143]} />
            <mesh name="key075" geometry={nodes.key075.geometry} material={materials.PaletteMaterial001} position={[-0.036, 0.003, -0.876]} scale={[1.208, 4, 2.143]} />
            <mesh name="key076" geometry={nodes.key076.geometry} material={materials.PaletteMaterial001} position={[0.052, 0.003, -0.876]} scale={[1.208, 4, 2.143]} />
            <mesh name="key077" geometry={nodes.key077.geometry} material={materials.PaletteMaterial001} position={[0.139, 0.003, -0.876]} scale={[1.208, 4, 2.143]} />
            <mesh name="key078" geometry={nodes.key078.geometry} material={materials.PaletteMaterial001} position={[0.227, 0.003, -0.876]} scale={[1.208, 4, 2.143]} />
            <mesh name="key079" geometry={nodes.key079.geometry} material={materials.PaletteMaterial001} position={[0.314, 0.003, -0.876]} scale={[1.208, 4, 2.143]} />
            <mesh name="key080" geometry={nodes.key080.geometry} material={materials.PaletteMaterial001} position={[0.408, 0.003, -0.876]} scale={[1.208, 4, 2.143]} />
            <mesh name="key081" geometry={nodes.key081.geometry} material={materials.PaletteMaterial001} position={[0.535, 0.003, -0.876]} scale={[1.208, 4, 2.143]} />
            <mesh name="key082" geometry={nodes.key082.geometry} material={materials.PaletteMaterial001} position={[0.629, 0.003, -0.876]} scale={[1.208, 4, 2.143]} />
            <mesh name="key083" geometry={nodes.key083.geometry} material={materials.PaletteMaterial001} position={[0.723, 0.003, -0.876]} scale={[1.208, 4, 2.143]} />
            <mesh name="key084" geometry={nodes.key084.geometry} material={materials.PaletteMaterial001} position={[0.817, 0.003, -0.876]} scale={[1.208, 4, 2.143]} />
            <mesh name="key085" geometry={nodes.key085.geometry} material={materials.PaletteMaterial001} position={[0.535, 0.003, -0.588]} scale={[1.208, 4, 4.667]} />
            <mesh name="key086" geometry={nodes.key086.geometry} material={materials.PaletteMaterial001} position={[0.629, 0.003, -0.588]} scale={[1.208, 4, 4.667]} />
            <mesh name="key087" geometry={nodes.key087.geometry} material={materials.PaletteMaterial001} position={[0.724, 0.003, -0.588]} scale={[1.208, 4, 4.667]} />
            <mesh name="key088" geometry={nodes.key088.geometry} material={materials.PaletteMaterial001} position={[0.818, 0.003, -0.588]} scale={[1.208, 4, 4.667]} />
            <mesh name="key089" geometry={nodes.key089.geometry} material={materials.PaletteMaterial001} position={[0.535, 0.003, -0.258]} scale={[1.208, 4, 4.667]} />
            <mesh name="key090" geometry={nodes.key090.geometry} material={materials.PaletteMaterial001} position={[0.629, 0.003, -0.258]} scale={[1.208, 4, 4.667]} />
            <mesh name="key091" geometry={nodes.key091.geometry} material={materials.PaletteMaterial001} position={[0.724, 0.003, -0.258]} scale={[1.208, 4, 4.667]} />
            <mesh name="key092" geometry={nodes.key092.geometry} material={materials.PaletteMaterial001} position={[0.535, 0.003, 0.075]} scale={[1.208, 4, 4.667]} />
            <mesh name="key093" geometry={nodes.key093.geometry} material={materials.PaletteMaterial001} position={[0.629, 0.003, 0.075]} scale={[1.208, 4, 4.667]} />
            <mesh name="key094" geometry={nodes.key094.geometry} material={materials.PaletteMaterial001} position={[0.724, 0.003, 0.075]} scale={[1.208, 4, 4.667]} />
            <mesh name="key095" geometry={nodes.key095.geometry} material={materials.PaletteMaterial001} position={[0.535, 0.003, 0.412]} scale={[1.208, 4, 4.667]} />
            <mesh name="key096" geometry={nodes.key096.geometry} material={materials.PaletteMaterial001} position={[0.629, 0.003, 0.412]} scale={[1.208, 4, 4.667]} />
            <mesh name="key097" geometry={nodes.key097.geometry} material={materials.PaletteMaterial001} position={[0.724, 0.003, 0.412]} scale={[1.208, 4, 4.667]} />
            <mesh name="key098" geometry={nodes.key098.geometry} material={materials.PaletteMaterial001} position={[0.724, 0.003, 0.753]} scale={[1.208, 4, 4.667]} />
            <mesh name="key099" geometry={nodes.key099.geometry} material={materials.PaletteMaterial001} position={[0.535, 0.003, 0.765]} scale={[1.208, 4, 4.667]} />
            <mesh name="key100" geometry={nodes.key100.geometry} material={materials.PaletteMaterial001} position={[0.818, 0.003, -0.255]} scale={[1.208, 4, 4.667]} />
            <mesh name="key101" geometry={nodes.key101.geometry} material={materials.PaletteMaterial001} position={[0.818, 0.003, 0.419]} scale={[1.208, 4, 4.667]} />
            <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.PaletteMaterial001} position={[0.786, -0.134, -0.838]} rotation={[1.623, 0, 0]} scale={[0.021, 0.076, 0.064]} />
          </mesh>
          <group name="Monitor" position={[0.139, 1.092, 0.028]} rotation={[Math.PI / 2, 0, 0]} scale={[0.733, 0.487, 0.578]}>
            <mesh name="Plane004_1" geometry={nodes.Plane004_1.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Plane004_2" geometry={nodes.Plane004_2.geometry} material={materials.MonitorDisplay0} />
            <mesh name="Plane004_3" geometry={nodes.Plane004_3.geometry} material={materials.MonitorDisplay1} />
            <mesh name="MonitorHold" geometry={nodes.MonitorHold.geometry} material={materials.PaletteMaterial001} position={[0.002, -1.811, 1.577]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.047, 0.165, 0.135]} />
            <mesh name="MonitorLegs" geometry={nodes.MonitorLegs.geometry} material={materials.PaletteMaterial001} position={[0.002, -1.748, 1.577]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.047, 0.165, 0.135]} />
          </group>
          <mesh name="Mouse" geometry={nodes.Mouse.geometry} material={materials.PaletteMaterial001} position={[0.619, 0.2, 0.546]} rotation={[0, 0.155, 0]} scale={[0.06, 0.16, 0.145]}>
            <mesh name="Mouse_pad" geometry={nodes.Mouse_pad.geometry} material={materials.Pad1} position={[-6.803, -0.073, -1.275]} rotation={[0, -0.109, 0]} scale={[10.163, 2.159, 3.541]} />
            <mesh name="Scroll" geometry={nodes.Scroll.geometry} material={materials.PaletteMaterial001} position={[0.203, 0.262, -0.604]} rotation={[-0.296, -0.089, -1.587]} scale={[-0.061, -0.061, -0.131]} />
          </mesh>
        </group>
        <group name="PC" position={[-1.438, 2.45, -3.706]} scale={[0.289, 0.831, 0.831]}>
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials.PaletteMaterial003} />
          <mesh name="Plane001_2" geometry={nodes.Plane001_2.geometry} material={materials.PaletteMaterial001} />
        </group>
        <mesh name="legsDesk" geometry={nodes.legsDesk.geometry} material={materials.PaletteMaterial001} position={[-1.598, 0.527, -2.99]} scale={0.157} />
        <mesh name="legsDesk001" geometry={nodes.legsDesk001.geometry} material={materials.PaletteMaterial001} position={[3.179, 1.918, -2.99]} scale={[0.157, 0.019, 0.157]} />
        <mesh name="PCin" geometry={nodes.PCin.geometry} material={materials.PaletteMaterial001} position={[-1.692, 3.024, -3.736]} rotation={[0, 0, -Math.PI / 2]} scale={[0.522, 0.522, 0.684]}>
          <group name="Cubein" position={[-0.414, 0.233, 0.456]} rotation={[0, 0, Math.PI / 2]} scale={[0.156, 0.331, 0.253]}>
            <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Cube004_1" geometry={nodes.Cube004_1.geometry} material={materials.PaletteMaterial004} />
          </group>
          <group name="Cubein001" position={[0.58, 0.254, 0.024]} rotation={[0, 0, Math.PI / 2]} scale={[0.256, 0.067, 0.679]}>
            <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Cube005_1" geometry={nodes.Cube005_1.geometry} material={materials.PaletteMaterial004} />
          </group>
          <mesh name="Lightin" geometry={nodes.Lightin.geometry} material={materials.PaletteMaterial004} position={[-0.922, 0, 0.041]} scale={[0.009, 1.07, 0.818]} />
          <mesh name="Lightin001" geometry={nodes.Lightin001.geometry} material={materials.PaletteMaterial004} position={[-0.026, 0, -0.885]} rotation={[0, Math.PI / 2, 0]} scale={[0.007, 1.07, 0.607]} />
          <group name="PLANEin" position={[0.086, 0.053, -0.294]} rotation={[0, 0, Math.PI / 2]} scale={[0.052, 0.8, 0.019]}>
            <mesh name="Plane055" geometry={nodes.Plane055.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Plane055_1" geometry={nodes.Plane055_1.geometry} material={materials.PaletteMaterial004} />
          </group>
        </mesh>
        <group name="Eevee" position={[-4.511, 3.875, -2.774]} rotation={[0, Math.PI / 4, 0]} scale={0.017}>
          <mesh name="Eevee_1" geometry={nodes.Eevee_1.geometry} material={materials.Material__12} />
          <mesh name="Eevee_2" geometry={nodes.Eevee_2.geometry} material={materials.Material__13} />
          <mesh name="Eevee_3" geometry={nodes.Eevee_3.geometry} material={materials.Material__14} />
        </group>
        <group name="Football" position={[-4.252, 4.975, -4.587]} rotation={[Math.PI / 2, 0, 0]} scale={0.272}>
          <mesh name="Solid002" geometry={nodes.Solid002.geometry} material={materials.PaletteMaterial008} />
          <mesh name="Solid002_1" geometry={nodes.Solid002_1.geometry} material={materials.PaletteMaterial008} />
        </group>
        <mesh name="Cello_hold" geometry={nodes.Cello_hold.geometry} material={materials.PaletteMaterial001} position={[-4.171, 3.77, -3.373]} rotation={[0, 0, -Math.PI / 2]} scale={0.065}>
          <mesh name="Torus" geometry={nodes.Torus.geometry} material={materials.PaletteMaterial001} position={[-0.336, 1.722, 0.109]} rotation={[0, 0, Math.PI / 2]} scale={-1.047} />
        </mesh>
        <group name="NintendoSwitch" position={[-3.933, 1.791, 0.174]} rotation={[0, 0, Math.PI / 2]} scale={[0.151, 0.145, 0.252]}>
          <mesh name="Plane075" geometry={nodes.Plane075.geometry} material={materials.PaletteMaterial008} />
          <mesh name="Plane075_1" geometry={nodes.Plane075_1.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Plane075_2" geometry={nodes.Plane075_2.geometry} material={materials.PaletteMaterial001} />
          <mesh name="NSBlue" geometry={nodes.NSBlue.geometry} material={materials.PaletteMaterial001} position={[0, -0.047, 0.869]} rotation={[0, 0, -Math.PI / 2]} scale={[1.061, 1.02, 0.613]}>
            <mesh name="Buttons001" geometry={nodes.Buttons001.geometry} material={materials.PaletteMaterial001} position={[0.146, -0.006, 0.504]} scale={[0.061, 0.061, 0.055]} />
            <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials.PaletteMaterial001} position={[-0.812, -0.004, 0.316]} rotation={[0, 0, Math.PI / 2]} scale={[0.025, 0.02, 0.058]} />
            <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials.PaletteMaterial001} position={[0.322, -0.002, 0.401]} rotation={[0, 0, Math.PI / 2]} scale={[0.027, 0.046, 0.046]} />
            <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials.PaletteMaterial001} position={[-1.01, -0.062, 0.548]} rotation={[Math.PI, -0.04, 1.571]} scale={[0.031, 0.031, 0.159]} />
            <mesh name="NSjoystick" geometry={nodes.NSjoystick.geometry} material={materials.PaletteMaterial001} position={[-0.528, -0.057, 0.51]} rotation={[0, 0, Math.PI / 2]} scale={[0.109, 0.141, 0.141]} />
          </mesh>
          <mesh name="NSRed" geometry={nodes.NSRed.geometry} material={materials.PaletteMaterial001} position={[-0.139, -0.047, -0.869]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[1.061, 1.02, 0.613]}>
            <mesh name="+But" geometry={nodes['+But'].geometry} material={materials.PaletteMaterial001} position={[-0.811, -0.134, 0.317]} rotation={[-Math.PI, 0, 0]} scale={0.055} />
            <mesh name="Buttons" geometry={nodes.Buttons.geometry} material={materials.PaletteMaterial001} position={[-0.385, -0.131, 0.509]} rotation={[-Math.PI, 0, 0]} scale={[0.061, 0.061, 0.055]} />
            <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials.PaletteMaterial001} position={[-1.01, -0.074, 0.539]} rotation={[Math.PI, -0.04, 1.571]} scale={[0.031, 0.031, 0.159]} />
            <mesh name="NSjoystick001" geometry={nodes.NSjoystick001.geometry} material={materials.PaletteMaterial001} position={[0.012, -0.079, 0.512]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={[0.109, 0.141, 0.141]} />
          </mesh>
        </group>
        <group name="Coffee_Table001" position={[0.239, 0.518, 1.163]} scale={[0.737, 0.403, 0.04]}>
          <mesh name="Cube018" geometry={nodes.Cube018.geometry} material={materials.Floor} />
          <mesh name="Cube018_1" geometry={nodes.Cube018_1.geometry} material={materials.PaletteMaterial001} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/GamingImpr-transformed.glb')
